In [22]:
# Importo librer√≠as necesarias
import numpy as np, pandas as pd

In [23]:
# Importo y leo el dataframe
europa = pd.read_csv('data\\paises.tsv', sep='\t')
europa

,"indic_de,geo\time",2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022
0,"JAN,AD",78115 b,78115,76246,:,:,71732,:,74794 e,76177,77543 e,:,79535
1,"JAN,AL",2907361,2903008,2897770,2892394,2885796,2875592,2876591,2870324,2862427,2845955,2829741,2793592
2,"JAN,AM",3262650,3274285,3026878,3017079,3010598,2998577,2986151,2972732,2965269,2959694,2963251,:
3,"JAN,AT",8375164,8408121,8451860,8507786,8584926,8700471,8772865,8822267,8858775,8901064,8932664,8978929
4,"JAN,AZ",9111078,9235085,9356483,9477119,9593038,9705643,9809981,9898085,9981457,10067108,10119133,10156366
5,"JAN,BA",3843183,3839265,3835645,3830911,3825334,3515982,3509728,3500295,3492018 p,:,:,:
6,"JAN,BE",11000638 b,11075889 b,11137974,11180840,11237274,11311117,11351727,11398589,11455519,11522440,11554767,11617623
7,"JAN,BG",7369431,7327224,7284552,7245677,7202198,7153784,7101859,7050034,7000039,6951482,6916548,6838937
8,"JAN,BY",9481193,9465150,9463840,9468154,9480868 e,9498364,9504704,9491823,9475174,9408350,:,:
9,"JAN,CH",7870134 b,7954662,8039060,8139631,8237666,8327126,8419550,8484130,8544527,8606033,8670300,8738791
10,"JAN,CY",839751,862011,865878,858000,847008,848319,854802,864236,875899,888005,896007,904705
11,"JAN,CZ",10486731,10505445,10516125,10512419,10538275,10553843,10578820,10610055,10649800,10693939,10494836 b,10516707 b
12,"JAN,DE",80222065 b,80327900,80523746,80767463,81197537,82175684,82521653,82792351,83019213,83166711,83155031,83237124
13,"JAN,DK",5560628,5580516,5602628,5627235,5659715,5707251,5748769,5781190,5806081,5822763,5840045,5873420
14,"JAN,EA19",334572589 b,335288924 b,336044966,337764352 b,338562121 b,339787987,340541142 b,341253004,341636902 be,342574791,342561034 p,342805884 bp
15,"JAN,EA20",:,:,:,:,:,:,:,:,:,:,:,346842500 bp
16,"JAN,EE",1329660,1325217,1320174,1315819,1314870 b,1315944,1315635,1319133,1324820,1328976,1330068,1331796
17,"JAN,EL",11123392,11086406,11003615,10926807,10858018,10783748,10768193,10741165,10724599,10718565,10678632,10459782
18,"JAN,ES",46667174,46818219,46727890,46512199,46449565,46440099,46528024,46658447,46937060,47332614,47398695,47432893
19,"JAN,EU27_2020",439942305 b,440552661 b,441257711,442883888 b,443666812 b,444802830,445534430 b,446208557 e,446559279 be,447485231 e,447000548 bep,446735291 bep
20,"JAN,FI",5375276,5401267,5426674,5451270,5471753,5487308,5503297,5513130,5517919,5525292,5533793,5548241
21,"JAN,FR",64978721,65276983,65600350,66165980 b,66458153,66638391,66809816,67026224,67290471,67485531,67656682 p,67871925 p
22,"JAN,FX",63070344,63375971,63697865,:,:,:,:,:,:,:,:,:
23,"JAN,GE",4469250,4497617,:,4490498,3729500 b,3720400,3726374,3729633,3723464,3716858,3728573,3688647
24,"JAN,HR",4289857,4275984,4262140,4246809,4225316,4190669,4154213,4105493,4076246,4058165,4036355,3862305
25,"JAN,HU",9985722,9931925 b,9908798,9877365,9855571,9830485,9797561,9778371,9772756,9769526,9730772,9689010
26,"JAN,IE",4570881,4589287,4609779,4637852,4677627,4726286,4784383,4830392,4904240 e,4964440,5006324,5060004
27,"JAN,IS",318452,319575,321857,325671,329100,332529,338349,348450,356991,364134,368792,376248
28,"JAN,IT",59364690,59394207,59685227,60782668,60795612,60665551,60589445,60483973,59816673 b,59641488,59236213,59030133
29,"JAN,LI",36149,36475,36838,37129,37366,37622,37810,38114,38378,38747,39055,39308
30,"JAN,LT",3052588,3003641,2971905,2943472,2921262,2888558,2847904,2808901,2794184,2794090,2795680,2805998
31,"JAN,LU",511840,524853 b,537039,549680,562958,576249,590667 b,602005,613894,626108,634730,645397
32,"JAN,LV",2074605,2044813,2023825,2001468,1986096,1968957,1950116,1934379,1919968,1907675,1893223,1875757
33,"JAN,MC",:,:,:,:,37700 e,38200,:,38300,38300 e,:,:,:
34,"JAN,MD",3560430,3559541,3559497,2869226 be,2844673 e,2824387 e,2779952 e,2730364 e,2686064 e,2640438 e,2597107 p,:
35,"JAN,ME",619850,620308,620893,621521,622099,622218,622387,622359,622182,621873,620739,617683
36,"JAN,MK",2057284,2059794,2062294 e,2065769 e,2069172 e,2071278 e,2073702 e,2075301,2077132,2076255,2068808,1837114
37,"JAN,MT",414989,417546,422509,429424,439691,450415,460297,475701,493559,514564,516100,520971
38,"JAN,NL",16655799,16730348,16779575,16829289,16900726,16979120,17081507,17181084,17282163,17407585,17475415,17590672
39,"JAN,NO",4920305,4985870,5051275,5107970,5166493,5210721,5258317,5295619,5328212,5367580,5391369,5425270
40,"JAN,PL",38062718,38063792,38062535,38017856,38005614,37967209,37972964,37976687 e,37972812,37958138 e,37840001 ep,37654247
41,"JAN,PT",10572721,10542398,10487289,10427301,10374822,10341330,10309573,10291027,10276617,10295909,10298252,10352042 bp
42,"JAN,RO",20199059,20095996,20020074,19947311,19870647,19760585,19643949,19533481,19414458,19328838 e,19201662,19042455 e
43,"JAN,RS",7251549 b,7216649,7181505,7146759,7114393,7076372,7040272,7001444,6963764,6926705,6871547,6797105
44,"JAN,RU",142856536,143056383,:,143666931,:,:,:,:,:,:,:,:
45,"JAN,SE",9415570,9482855,9555893,9644864,9747355,9851017,9995153,10120242,10230185,10327589,10379295,10452326
46,"JAN,SI",2050189,2055496,2058821,2061085,2062874,2064188,2065895,2066880,2080908,2095861,2108977,2107180
47,"JAN,SK",5392446,5404322,5410836,5415949,5421349,5426252,5435343,5443120,5450421,5457873,5459781,5434712
48,"JAN,SM",31863,33376,33562,32520,32789,33005,33196,34453,34590,34735,34805,33698
49,"JAN,TR",73722988,74724269,75627384,76667864,77695904,78741053,79814871,80810525,82003882 be,83154997,83614362,84680273
50,"JAN,UA",45598179,45453282,45372692,45245894,42759661 b,42590879,42414905,42216766,41983564,41732779,41418717,40997698 e
51,"JAN,UK",63022532,63495088,63905342,64351203,64853393,65379044,65844142,66273576,66647112,67025542,:,:
52,"JAN,XK",1794180 b,1780021 e,1815606 e,1820631 e,1804944 e,1771604 e,1783531 e,1798506,1795666,1782115,1798188 e,:

In [24]:
# Elimino columnas que a primera vista s√© que no necesito
europa = europa.drop(columns= ['2011 ', '2012 '])

In [25]:
# Renombro la columna del pa√≠s
europa.rename(columns={'indic_de,geo\\time' : 'Country'}, inplace = True)

In [26]:
# Corrijo los valores de pa√≠ses.
europa['Country'] = europa['Country'].apply(lambda valor: valor[-2:])

In [27]:
siglas = {'AT': 'Austria',
        'BA': 'Bosnia y Herzegovina',
        'BE': 'B√©lgica',
        'CH': 'Suiza',
        'CY': 'Chipre',
        'CZ': 'Rep√∫blica Checa',
        'DE': 'Alemania',
        'DK': 'Dinamarca',
        'EE': 'Estonia',
        'ES': 'Espa√±a',
        'FI': 'Finlandia',
        'FR': 'Francia',
        'UK': 'Reino Unido',
        'EL': 'Grecia',
        'HR': 'Croacia',
        'IS': 'Islandia',
        'IT': 'Italia',
        'LT': 'Lituania',
        'LV': 'Latvia',
        'MT': 'Malta',
        'NL': 'Pa√≠ses Bajos',
        'NO': 'Noruega',
        'PL': 'Polonia',
        'PT': 'Portugal',
        'RO': 'Rumania',
        'RS': 'Serbia',
        'SE': 'Suecia',
        'SI': 'Eslovenia',
        'SK': 'Eslovaquia',
        'TR': 'Turqu√≠a'}

In [28]:
# Cambio de siglas a nombres completos
europa['Country'] = europa['Country'].apply(lambda valor: siglas.get(valor))

In [29]:
# Elimino pa√≠ses que no coinciden con el dataframe de aguas residuales
europa = europa.dropna(subset=['Country'])

In [30]:
# Indico los pa√≠ses como √≠ndice.
europa.set_index(europa.columns[0], inplace= True)

In [31]:
# Elimino las letras sobrantes de los datos.
import re

for columna in europa.columns:
    europa[columna] = europa[columna].replace(to_replace=r'[A-Za-z]+$', value='', regex=True)

In [32]:
# Reemplazo el valor ":" a NaN
europa = europa.replace(to_replace=r'^\s*:\s*$', value=np.nan, regex=True)

In [33]:
europa = europa.apply(pd.to_numeric)

In [34]:
# Leo un dataframe diferente  que contiene algunos de los datos faltantes, para complementar el primero.
missing = pd.read_csv('data/missing.csv')

In [35]:
# Renombro la columna del nuevo dataframe para poder combinarlos.
missing.rename(columns={'Country Name' : 'Country'}, inplace = True)

In [36]:
missing.drop(columns=['Unnamed: 0'], inplace= True)
missing.set_index('Country', inplace= True)

In [37]:
# Me quedo solo con las columnas que tienen valores faltantes en el dataframe original
missing = missing.iloc[:, -3:-1]

In [38]:
missing['2021']

Country
Bosnia y Herzegovina     3270943
Reino Unido             67326569
Name: 2021, dtype: int64

In [39]:
# Relleno valores vac√≠os con el datafrane, y los m√°s recientes con el √∫ltimo registrado.
europa['2020 '].fillna(missing['2020'], inplace=True)

In [40]:
europa

,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022
Country,,,,,,,,,,
Austria,8451860,8507786,8584926,8700471,8772865,8822267,8858775,8901064.0,8932664.0,8978929.0
Bosnia y Herzegovina,3835645,3830911,3825334,3515982,3509728,3500295,3492018,3318407.0,NaN,NaN
B√©lgica,11137974,11180840,11237274,11311117,11351727,11398589,11455519,11522440.0,11554767.0,11617623.0
Suiza,8039060,8139631,8237666,8327126,8419550,8484130,8544527,8606033.0,8670300.0,8738791.0
Chipre,865878,858000,847008,848319,854802,864236,875899,888005.0,896007.0,904705.0
Rep√∫blica Checa,10516125,10512419,10538275,10553843,10578820,10610055,10649800,10693939.0,10494836.0,10516707.0
Alemania,80523746,80767463,81197537,82175684,82521653,82792351,83019213,83166711.0,83155031.0,83237124.0
Dinamarca,5602628,5627235,5659715,5707251,5748769,5781190,5806081,5822763.0,5840045.0,5873420.0
Estonia,1320174,1315819,1314870,1315944,1315635,1319133,1324820,1328976.0,1330068.0,1331796.0
Grecia,11003615,10926807,10858018,10783748,10768193,10741165,10724599,10718565.0,10678632.0,10459782.0
Espa√±a,46727890,46512199,46449565,46440099,46528024,46658447,46937060,47332614.0,47398695.0,47432893.0
Finlandia,5426674,5451270,5471753,5487308,5503297,5513130,5517919,5525292.0,5533793.0,5548241.0
Francia,65600350,66165980,66458153,66638391,66809816,67026224,67290471,67485531.0,67656682.0,67871925.0
Croacia,4262140,4246809,4225316,4190669,4154213,4105493,4076246,4058165.0,4036355.0,3862305.0
Islandia,321857,325671,329100,332529,338349,348450,356991,364134.0,368792.0,376248.0
Italia,59685227,60782668,60795612,60665551,60589445,60483973,59816673,59641488.0,59236213.0,59030133.0
Lituania,2971905,2943472,2921262,2888558,2847904,2808901,2794184,2794090.0,2795680.0,2805998.0
Latvia,2023825,2001468,1986096,1968957,1950116,1934379,1919968,1907675.0,1893223.0,1875757.0
Malta,422509,429424,439691,450415,460297,475701,493559,514564.0,516100.0,520971.0
Pa√≠ses Bajos,16779575,16829289,16900726,16979120,17081507,17181084,17282163,17407585.0,17475415.0,17590672.0
Noruega,5051275,5107970,5166493,5210721,5258317,5295619,5328212,5367580.0,5391369.0,5425270.0
Polonia,38062535,38017856,38005614,37967209,37972964,37976687,37972812,37958138.0,37840001.0,37654247.0
Portugal,10487289,10427301,10374822,10341330,10309573,10291027,10276617,10295909.0,10298252.0,10352042.0
Rumania,20020074,19947311,19870647,19760585,19643949,19533481,19414458,19328838.0,19201662.0,19042455.0
Serbia,7181505,7146759,7114393,7076372,7040272,7001444,6963764,6926705.0,6871547.0,6797105.0
Suecia,9555893,9644864,9747355,9851017,9995153,10120242,10230185,10327589.0,10379295.0,10452326.0
Eslovenia,2058821,2061085,2062874,2064188,2065895,2066880,2080908,2095861.0,2108977.0,2107180.0
Eslovaquia,5410836,5415949,5421349,5426252,5435343,5443120,5450421,5457873.0,5459781.0,5434712.0
Turqu√≠a,75627384,76667864,77695904,78741053,79814871,80810525,82003882,83154997.0,83614362.0,84680273.0
Reino Unido,63905342,64351203,64853393,65379044,65844142,66273576,66647112,67025542.0,NaN,NaN

In [41]:
europa['2021 '].fillna(missing['2021'], inplace=True)

In [42]:
europa

,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022
Country,,,,,,,,,,
Austria,8451860,8507786,8584926,8700471,8772865,8822267,8858775,8901064.0,8932664.0,8978929.0
Bosnia y Herzegovina,3835645,3830911,3825334,3515982,3509728,3500295,3492018,3318407.0,3270943.0,NaN
B√©lgica,11137974,11180840,11237274,11311117,11351727,11398589,11455519,11522440.0,11554767.0,11617623.0
Suiza,8039060,8139631,8237666,8327126,8419550,8484130,8544527,8606033.0,8670300.0,8738791.0
Chipre,865878,858000,847008,848319,854802,864236,875899,888005.0,896007.0,904705.0
Rep√∫blica Checa,10516125,10512419,10538275,10553843,10578820,10610055,10649800,10693939.0,10494836.0,10516707.0
Alemania,80523746,80767463,81197537,82175684,82521653,82792351,83019213,83166711.0,83155031.0,83237124.0
Dinamarca,5602628,5627235,5659715,5707251,5748769,5781190,5806081,5822763.0,5840045.0,5873420.0
Estonia,1320174,1315819,1314870,1315944,1315635,1319133,1324820,1328976.0,1330068.0,1331796.0
Grecia,11003615,10926807,10858018,10783748,10768193,10741165,10724599,10718565.0,10678632.0,10459782.0
Espa√±a,46727890,46512199,46449565,46440099,46528024,46658447,46937060,47332614.0,47398695.0,47432893.0
Finlandia,5426674,5451270,5471753,5487308,5503297,5513130,5517919,5525292.0,5533793.0,5548241.0
Francia,65600350,66165980,66458153,66638391,66809816,67026224,67290471,67485531.0,67656682.0,67871925.0
Croacia,4262140,4246809,4225316,4190669,4154213,4105493,4076246,4058165.0,4036355.0,3862305.0
Islandia,321857,325671,329100,332529,338349,348450,356991,364134.0,368792.0,376248.0
Italia,59685227,60782668,60795612,60665551,60589445,60483973,59816673,59641488.0,59236213.0,59030133.0
Lituania,2971905,2943472,2921262,2888558,2847904,2808901,2794184,2794090.0,2795680.0,2805998.0
Latvia,2023825,2001468,1986096,1968957,1950116,1934379,1919968,1907675.0,1893223.0,1875757.0
Malta,422509,429424,439691,450415,460297,475701,493559,514564.0,516100.0,520971.0
Pa√≠ses Bajos,16779575,16829289,16900726,16979120,17081507,17181084,17282163,17407585.0,17475415.0,17590672.0
Noruega,5051275,5107970,5166493,5210721,5258317,5295619,5328212,5367580.0,5391369.0,5425270.0
Polonia,38062535,38017856,38005614,37967209,37972964,37976687,37972812,37958138.0,37840001.0,37654247.0
Portugal,10487289,10427301,10374822,10341330,10309573,10291027,10276617,10295909.0,10298252.0,10352042.0
Rumania,20020074,19947311,19870647,19760585,19643949,19533481,19414458,19328838.0,19201662.0,19042455.0
Serbia,7181505,7146759,7114393,7076372,7040272,7001444,6963764,6926705.0,6871547.0,6797105.0
Suecia,9555893,9644864,9747355,9851017,9995153,10120242,10230185,10327589.0,10379295.0,10452326.0
Eslovenia,2058821,2061085,2062874,2064188,2065895,2066880,2080908,2095861.0,2108977.0,2107180.0
Eslovaquia,5410836,5415949,5421349,5426252,5435343,5443120,5450421,5457873.0,5459781.0,5434712.0
Turqu√≠a,75627384,76667864,77695904,78741053,79814871,80810525,82003882,83154997.0,83614362.0,84680273.0
Reino Unido,63905342,64351203,64853393,65379044,65844142,66273576,66647112,67025542.0,67326569.0,NaN

In [46]:
europa = europa.fillna(method='ffill', axis=1)

In [48]:
europa.to_csv('../Aguas/data/europa.csv')